"""Renombrar columna register a registration_number en Bull 2

Revision ID: 02547bf8b47c
Revises: fb7d5ae8265c
Create Date: 2025-06-30 10:04:39.362197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02547bf8b47c'
down_revision: Union[str, None] = 'fb7d5ae8265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulls', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.drop_column('bulls', 'register')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulls', sa.Column('register', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('bulls', 'registration_number')
    # ### end Alembic commands ###
