"""add_calendar_tables

Revision ID: 26b2003a97d1
Revises: 66a24cafacf7
Create Date: 2025-08-07 19:32:54.465689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b2003a97d1'
down_revision: Union[str, None] = '66a24cafacf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_task_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('color_background', sa.VARCHAR(length=7), nullable=True),
    sa.Column('color_foreground', sa.VARCHAR(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_task_types_id'), 'calendar_task_types', ['id'], unique=False)
    op.create_table('calendar_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_templates_id'), 'calendar_templates', ['id'], unique=False)
    op.create_table('calendar_tasks',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('veterinarian', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('suffix', sa.String(length=100), nullable=True),
    sa.Column('task_group_id', sa.String(length=100), nullable=True),
    sa.Column('color_background', sa.VARCHAR(length=7), nullable=True),
    sa.Column('color_foreground', sa.VARCHAR(length=7), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_tasks_id'), 'calendar_tasks', ['id'], unique=False)
    op.create_table('calendar_template_tasks',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_type_id'], ['calendar_task_types.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['calendar_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_template_tasks_id'), 'calendar_template_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_template_tasks_id'), table_name='calendar_template_tasks')
    op.drop_table('calendar_template_tasks')
    op.drop_index(op.f('ix_calendar_tasks_id'), table_name='calendar_tasks')
    op.drop_table('calendar_tasks')
    op.drop_index(op.f('ix_calendar_templates_id'), table_name='calendar_templates')
    op.drop_table('calendar_templates')
    op.drop_index(op.f('ix_calendar_task_types_id'), table_name='calendar_task_types')
    op.drop_table('calendar_task_types')
    # ### end Alembic commands ###
