"""Add cliente_id to facturacion table

Revision ID: 3dc8b1fc5fdd
Revises: 8ce907b7a09c
Create Date: 2025-10-23 11:44:05.897334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc8b1fc5fdd'
down_revision: Union[str, None] = '8ce907b7a09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturacion', sa.Column('cliente_id', sa.Integer(), nullable=False, comment='ID del cliente al que pertenece la factura'))
    op.create_foreign_key(None, 'facturacion', 'users', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturacion', type_='foreignkey')
    op.drop_column('facturacion', 'cliente_id')
    # ### end Alembic commands ###
