"""Crear tabla de asociacion para produccion y salidas

Revision ID: 5a396d56b0aa
Revises: 
Create Date: 2025-06-30 09:11:14.265554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a396d56b0aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_code'), 'races', ['code'], unique=True)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sexes',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sexes_code'), 'sexes', ['code'], unique=True)
    op.create_index(op.f('ix_sexes_id'), 'sexes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('number_document', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('type_document', sa.Enum('identity_card', 'passport', 'other', name='documenttype'), nullable=False),
    sa.Column('pass_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_number_document'), 'users', ['number_document'], unique=True)
    op.create_table('bulls',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('register', sa.String(length=50), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('escalerilla', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('sex_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='bullstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['sex_id'], ['sexes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulls_id'), 'bulls', ['id'], unique=False)
    op.create_table('produccion_embrionaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_opu', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('finca', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('envase', sa.String(length=100), nullable=False),
    sa.Column('fecha_transferencia', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produccion_embrionaria_id'), 'produccion_embrionaria', ['id'], unique=False)
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_user_id'), 'role_user', ['id'], unique=False)
    op.create_table('inputs',
    sa.Column('escalarilla', sa.String(length=100), nullable=False),
    sa.Column('bull_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Enum('pending', 'processing', 'completed', 'cancelled', name='inputstatus'), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('fv', sa.DateTime(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_taken', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bull_id'], ['bulls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_id'), 'inputs', ['id'], unique=False)
    op.create_table('opus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('toro_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('toro', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('donante_code', sa.String(length=100), nullable=False),
    sa.Column('gi', sa.Integer(), nullable=False),
    sa.Column('gii', sa.Integer(), nullable=False),
    sa.Column('giii', sa.Integer(), nullable=False),
    sa.Column('viables', sa.Integer(), nullable=False),
    sa.Column('otros', sa.Integer(), nullable=False),
    sa.Column('total_oocitos', sa.Integer(), nullable=False),
    sa.Column('ctv', sa.Integer(), nullable=False),
    sa.Column('clivados', sa.Integer(), nullable=False),
    sa.Column('porcentaje_cliv', sa.String(length=10), nullable=False),
    sa.Column('prevision', sa.Integer(), nullable=False),
    sa.Column('porcentaje_prevision', sa.String(length=10), nullable=False),
    sa.Column('empaque', sa.Integer(), nullable=False),
    sa.Column('porcentaje_empaque', sa.String(length=10), nullable=False),
    sa.Column('vt_dt', sa.Integer(), nullable=True),
    sa.Column('porcentaje_vtdt', sa.String(length=10), nullable=True),
    sa.Column('total_embriones', sa.Integer(), nullable=False),
    sa.Column('porcentaje_total_embriones', sa.String(length=10), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=True),
    sa.Column('finca', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('produccion_embrionaria_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['produccion_embrionaria_id'], ['produccion_embrionaria.id'], ),
    sa.ForeignKeyConstraint(['toro_id'], ['bulls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opus_id'), 'opus', ['id'], unique=False)
    op.create_table('outputs',
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('output_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_output', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputs_id'), 'outputs', ['id'], unique=False)
    op.create_table('produccion_embrionaria_output',
    sa.Column('produccion_embrionaria_id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.id'], ),
    sa.ForeignKeyConstraint(['produccion_embrionaria_id'], ['produccion_embrionaria.id'], ),
    sa.PrimaryKeyConstraint('produccion_embrionaria_id', 'output_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produccion_embrionaria_output')
    op.drop_index(op.f('ix_outputs_id'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_opus_id'), table_name='opus')
    op.drop_table('opus')
    op.drop_index(op.f('ix_inputs_id'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_role_user_id'), table_name='role_user')
    op.drop_table('role_user')
    op.drop_index(op.f('ix_produccion_embrionaria_id'), table_name='produccion_embrionaria')
    op.drop_table('produccion_embrionaria')
    op.drop_index(op.f('ix_bulls_id'), table_name='bulls')
    op.drop_table('bulls')
    op.drop_index(op.f('ix_users_number_document'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sexes_id'), table_name='sexes')
    op.drop_index(op.f('ix_sexes_code'), table_name='sexes')
    op.drop_table('sexes')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_index(op.f('ix_races_code'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
