"""add initial_report field to transferencias table

Revision ID: 66a24cafacf7
Revises: c7a96a0872dd
Create Date: 2025-07-27 22:00:44.625504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66a24cafacf7'
down_revision: Union[str, None] = 'c7a96a0872dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_transfers', 'donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'raza_donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'toro',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'toro_raza',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'estado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'receptora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'horario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'dx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'dxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'dxxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('transferencias', sa.Column('initial_report', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transferencias', 'initial_report')
    op.alter_column('report_transfers', 'dxxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'dxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'dx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'horario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'receptora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'estado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'toro_raza',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'toro',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'raza_donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
