"""Add facturacion and factura_detalle models

Revision ID: 87fa72d1b654
Revises: 26b2003a97d1
Create Date: 2025-10-22 23:55:10.112461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fa72d1b654'
down_revision: Union[str, None] = '26b2003a97d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturacion',
    sa.Column('id_factura', sa.String(length=20), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto_pagar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'vencido', 'pagado', name='estadofactura'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturacion_id'), 'facturacion', ['id'], unique=False)
    op.create_index(op.f('ix_facturacion_id_factura'), 'facturacion', ['id_factura'], unique=True)
    op.create_table('factura_detalle',
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_detalle_id'), 'factura_detalle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factura_detalle_id'), table_name='factura_detalle')
    op.drop_table('factura_detalle')
    op.drop_index(op.f('ix_facturacion_id_factura'), table_name='facturacion')
    op.drop_index(op.f('ix_facturacion_id'), table_name='facturacion')
    op.drop_table('facturacion')
    # ### end Alembic commands ###
