"""Add facturacion, factura_detalle, pagos tables with IVA and fecha_vencimiento fields

Revision ID: 8ce907b7a09c
Revises: 13ececdeb738
Create Date: 2025-10-23 11:05:51.899617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce907b7a09c'
down_revision: Union[str, None] = '13ececdeb738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'completado', 'fallido', 'cancelado', name='estadopago'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False, comment='Efectivo, Transferencia, Tarjeta, PSE, etc.'),
    sa.Column('referencia', sa.String(length=100), nullable=True, comment='Número de referencia del pago'),
    sa.Column('observaciones', sa.Text(), nullable=True, comment='Observaciones sobre el pago'),
    sa.Column('doc_type', sa.String(length=10), nullable=True, comment='Tipo de documento (CC, CE, etc.)'),
    sa.Column('document', sa.String(length=20), nullable=True, comment='Número de documento'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Nombre del pagador'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Apellido del pagador'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email del pagador'),
    sa.Column('ind_country', sa.String(length=5), nullable=True, comment='Código país (57=Colombia)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Teléfono del pagador'),
    sa.Column('country', sa.String(length=5), nullable=True, comment='Código país'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Ciudad del pagador'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='Dirección del pagador'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='IP del cliente'),
    sa.Column('currency', sa.String(length=5), nullable=True, comment='Moneda'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descripción del pago'),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True, comment='Valor del pago'),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True, comment='Impuestos'),
    sa.Column('ico', sa.Numeric(precision=10, scale=2), nullable=True, comment='ICO'),
    sa.Column('tax_base', sa.Numeric(precision=10, scale=2), nullable=True, comment='Base imponible'),
    sa.Column('url_response', sa.String(length=500), nullable=True, comment='URL de respuesta'),
    sa.Column('url_confirmation', sa.String(length=500), nullable=True, comment='URL de confirmación'),
    sa.Column('method_confirmation', sa.String(length=10), nullable=True, comment='Método confirmación'),
    sa.Column('ref_payco', sa.String(length=50), nullable=True, comment='Referencia de ePayco'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='ID de transacción'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Nombre del banco'),
    sa.Column('bank_url', sa.String(length=500), nullable=True, comment='URL del banco'),
    sa.Column('response_code', sa.String(length=10), nullable=True, comment='Código de respuesta'),
    sa.Column('response_message', sa.String(length=500), nullable=True, comment='Mensaje de respuesta'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.add_column('factura_detalle', sa.Column('embrio_fresco', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('embrio_congelado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('material_campo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('nitrogeno', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('mensajeria', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('pajilla_semen', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('fundas_te', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('factura_detalle', sa.Column('iva', sa.Numeric(precision=5, scale=2), nullable=False, comment='Porcentaje de IVA'))
    op.add_column('facturacion', sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True, comment='Fecha límite de pago'))
    op.add_column('facturacion', sa.Column('monto_base', sa.Numeric(precision=10, scale=2), nullable=True, comment='Valor base'))
    op.add_column('facturacion', sa.Column('iva', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje de IVA'))
    op.add_column('facturacion', sa.Column('valor_iva', sa.Numeric(precision=10, scale=2), nullable=True, comment='Valor del IVA'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturacion', 'valor_iva')
    op.drop_column('facturacion', 'iva')
    op.drop_column('facturacion', 'monto_base')
    op.drop_column('facturacion', 'fecha_vencimiento')
    op.drop_column('factura_detalle', 'iva')
    op.drop_column('factura_detalle', 'fundas_te')
    op.drop_column('factura_detalle', 'pajilla_semen')
    op.drop_column('factura_detalle', 'mensajeria')
    op.drop_column('factura_detalle', 'nitrogeno')
    op.drop_column('factura_detalle', 'material_campo')
    op.drop_column('factura_detalle', 'embrio_congelado')
    op.drop_column('factura_detalle', 'embrio_fresco')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
