"""add transferencia and report_transfer tables

Revision ID: c37493af8a62
Revises: f7cc028e3a4f
Create Date: 2025-07-27 21:12:40.999888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37493af8a62'
down_revision: Union[str, None] = 'f7cc028e3a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_transferencia', sa.Date(), nullable=False),
    sa.Column('veterinario_responsable', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('finca', sa.String(length=100), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('produccion_embrionaria_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produccion_embrionaria_id'], ['produccion_embrionaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_id'), 'transferencias', ['id'], unique=False)
    op.create_table('report_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donadora', sa.String(length=100), nullable=False),
    sa.Column('raza_donadora', sa.String(length=100), nullable=False),
    sa.Column('toro', sa.String(length=100), nullable=False),
    sa.Column('toro_raza', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('receptora', sa.String(length=100), nullable=False),
    sa.Column('horario', sa.String(length=100), nullable=False),
    sa.Column('dx', sa.String(length=100), nullable=False),
    sa.Column('dxx', sa.String(length=100), nullable=False),
    sa.Column('dxxx', sa.String(length=100), nullable=False),
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_transfers_id'), 'report_transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_transfers_id'), table_name='report_transfers')
    op.drop_table('report_transfers')
    op.drop_index(op.f('ix_transferencias_id'), table_name='transferencias')
    op.drop_table('transferencias')
    # ### end Alembic commands ###
