"""add cliente_id to transferencias table

Revision ID: c7a96a0872dd
Revises: c37493af8a62
Create Date: 2025-07-27 21:53:41.427219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7a96a0872dd'
down_revision: Union[str, None] = 'c37493af8a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_transfers', 'donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'raza_donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'toro',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'toro_raza',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'estado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'receptora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'horario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'dx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'dxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report_transfers', 'dxxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('transferencias', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transferencias', 'users', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferencias', type_='foreignkey')
    op.drop_column('transferencias', 'cliente_id')
    op.alter_column('report_transfers', 'dxxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'dxx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'dx',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'horario',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'receptora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'estado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'toro_raza',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'toro',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'raza_donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('report_transfers', 'donadora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
