"""Add aplica_iva field to facturacion table

Revision ID: ca47759319d1
Revises: 3dc8b1fc5fdd
Create Date: 2025-10-23 11:51:18.889963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca47759319d1'
down_revision: Union[str, None] = '3dc8b1fc5fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturacion', sa.Column('aplica_iva', sa.Boolean(), nullable=False, comment='Indica si aplica IVA a la factura'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturacion', 'aplica_iva')
    # ### end Alembic commands ###
