"""Renombrar columna register a registration_number en Bull

Revision ID: fb7d5ae8265c
Revises: 5a396d56b0aa
Create Date: 2025-06-30 10:02:09.833147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7d5ae8265c'
down_revision: Union[str, None] = '5a396d56b0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
